In [1]:
import numpy as pd

In [4]:


# Create NumPy array
a = np.array([1, 2, 3, 4])

print(a)


[1 2 3 4]


In [5]:
a[-1]

np.int64(4)

In [6]:
b=np.array([1,2,3,4,5,6,7,8,9])
b[0:9]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
b=np.array([1,2,3,4,5,6,7,8,9])
b[-1:5]

array([], dtype=int64)

In [9]:
c=b.copy()
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
d=b.view()
d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
b[0]=1
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b=a.reshape(4,3)
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [14]:
c=np.array([13,14,15])
d=np.concatenate((a,c))

In [15]:
np.array_split(d,2)

[array([1, 2, 3, 4, 5, 6, 7, 8]), array([ 9, 10, 11, 12, 13, 14, 15])]

In [16]:
np.where(d==4)

(array([3]),)

In [17]:
np.where(d%2==0)

(array([ 1,  3,  5,  7,  9, 11, 13]),)

In [19]:
c=np.array([3,4,2,10,5])
np.sort(c)

array([ 2,  3,  4,  5, 10])

In [20]:
c=np.array([[2,3,1,6],[5,1,2,4]])
np.sort(c)

array([[1, 2, 3, 6],
       [1, 2, 4, 5]])

In [21]:
c=np.array(['apple','orange','banana','mango'])
np.sort(c)

array(['apple', 'banana', 'mango', 'orange'], dtype='<U6')

In [22]:
np.random.rand(10)

array([0.45028712, 0.7137898 , 0.37689113, 0.50880877, 0.12977821,
       0.42920749, 0.60476411, 0.46083188, 0.84201987, 0.88858537])

In [23]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [24]:
np.ones(2)

array([1., 1.])

In [25]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])